import React from "react";
import DashboardHeader from "../../_components/dashboard/header";
import CustomersTable from "@/components/ecommerce/table/customers/customers-table";

export const metadata = {
  title: "Admin Dashboard | Customers",
  description: "Generated by create next app",
};

const CategoryPage = () => {
  const breadcrumbs = [
    { name: "Dashboard", href: "/dashboard" },
    { name: "Customers" },
  ];

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] min-h-screen space-y-4">
        <div className="w-full">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-2xl font-bold">Customers</h1>
            </div>
          </div>
          <CustomersTable />
        </div>
      </div>
    </>
  );
};

export default CategoryPage;
