import React from "react";
import DashboardHeader from "../../../_components/dashboard/header";
import { getAllCategories, getSinglePost } from "@/service/blog/blogService";
import EditBlogTitleForm from "../../_components/form/edit-blog-title-form";
import EditBlogDescriptionForm from "../../_components/form/edit-blog-description-form";
import EditBlogCategoryForm from "../../_components/form/edit-blog-category-form";
import EditBlogImageUploadForm from "../../_components/form/edit-blog-image-upload-form";

export const metadata = {
  title: "Admin Dashboard | Edit Post",
  description: "Generated by create next app",
};

const breadcrumbs = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Blogs and Articles", href: "/dashboard/blog" },
  { name: "Edit blog post" },
];

const EditBlogPage = async ({ params }) => {
  const response = await getSinglePost(params.blogId);
  const { categories } = await getAllCategories();

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] space-y-4">
        <h1 className="font-bold text-[20px]">Edit Post</h1>
        <div className="w-full flex md:flex-row flex-col gap-5 justify-between">
          <div className="w-full space-y-5  h-fit ">
            <EditBlogTitleForm
              name={response?.blogPost?.title}
              id={response?.blogPost?.id}
            />
            <EditBlogCategoryForm
              id={response?.blogPost?.id}
              options={categories?.map((category) => ({
                label: category.name,
                value: category.id,
              }))}
            />
            <EditBlogDescriptionForm
              content={response?.blogPost?.content}
              id={response?.blogPost?.id}
            />
            <EditBlogImageUploadForm
              images={response?.blogPost?.images}
              id={response?.blogPost?.id}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default EditBlogPage;
