import React from "react";
import OrdersTable from "@/components/ecommerce/table/orders/order-table";
import DashboardHeader from "../../_components/dashboard/header";

export const metadata = {
  title: "Admin Dashboard | Orders",
  description: "Generated by create next app",
};

const EcommercePage = () => {
  const breadcrumbs = [
    { name: "Dashboard", href: "/dashboard" },
    { name: "Orders" },
  ];

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] min-h-screen space-y-4">
        <div className="w-full">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-2xl font-bold">Orders</h1>
            </div>
          </div>
          <OrdersTable />
        </div>
      </div>
    </>
  );
};

export default EcommercePage;
