import React from "react";
import ProjectTitleForm from "../_component/form/project-title-form";
import DashboardHeader from "../../_components/dashboard/header";
import ProjectCategoryForm from "../_component/form/project-category-form";
import ProjectMediaTypeForm from "../_component/form/project-media-type-form";
import ProjectFileUploadForm from "../_component/form/project-file-upload-form";
import ProjectDescriptionForm from "../_component/form/project-description-form";
import ProjectFormSubmitButton from "../_component/form/project-submit-form-button";

export const metadata = {
  title: "Admin Dashboard | New project",
  keywords: "admin, dashboard, project, create, new project",
  description: "Generated by create next app",
};

const NewProject = () => {
  const breadcrumbs = [
    { name: "Dashboard", href: "/dashboard" },
    { name: "projects", href: "/dashboard/project" },
    { name: "New project" },
  ];

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] space-y-4">
        <h1 className="font-bold text-[20px]">Create a new Project</h1>
        <div className="w-full flex md:flex-row flex-col gap-5 justify-between">
          <div className="w-full space-y-5  h-fit ">
            <ProjectTitleForm />
            <ProjectCategoryForm />
            <ProjectMediaTypeForm />
            <ProjectFileUploadForm />
            <ProjectDescriptionForm />
            <ProjectFormSubmitButton />
          </div>
        </div>
      </div>
    </>
  );
};

export default NewProject;
