import DashboardHeader from "@/app/(admin)/dashboard/_components/dashboard/header";
import EditProductBriefDescriptionForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-brief-description-form";
import EditProductCategoryForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-category-form";
import EditProductDescriptionForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-description-form";
import EditProductDiscountForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-discount-form";
import EditProductImageUploadForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-image-upload-form";
import EditProductManufacturerForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-manufacture-form";
import EditProductPriceForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-price-form";
import EditProductStockForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-stock-form";
import EditProductTagForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-tag-form";
import EditProductTitleForm from "@/app/(admin)/dashboard/_components/ecommerce/edit-product-title-form";

import {
  getAllCategories,
  getSingleProduct,
} from "@/service/ecommerce/productService";
import React from "react";

export const metadata = {
  title: "Admin Dashboard | Edit Product",
  description: "Generated by create next app",
};

const breadcrumbs = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Ecommerce", href: "/dashboard/ecommerce" },
  { name: "Products", href: "/dashboard/ecommerce/products" },
  { name: "Edit product" },
];

const EditProductPage = async ({ params }) => {
  const response = await getSingleProduct(params.productId);
  const { categories } = await getAllCategories();

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] space-y-4">
        <h1 className="font-bold text-[20px]">Edit Product</h1>
        <div className="w-full flex md:flex-row flex-col gap-5 justify-between">
          <div className="w-full md:w-2/3 space-y-5  h-fit ">
            {/* <EditProductTitleForm
              name={response?.product?.name}
              id={response?.product?.id}
            />
            <EditProductDescriptionForm
              product_description={response?.product?.full_description}
              id={response?.product?.id}
            /> */}
            <EditProductImageUploadForm
              product_main_image={response.product.product_main_image}
              product_images={response.product.product_images}
              id={response?.product?.id}
            />
            {/* <ProductVarientForm /> */}
          </div>
          <div className="w-full md:w-2/6 h-fit space-y-5">
            <EditProductPriceForm
              product_price={response?.product?.price}
              id={response?.product?.id}
            />
            <EditProductStockForm
              stock={response?.product?.stock}
              id={response?.product?.id}
            />
            <EditProductCategoryForm
              id={response?.product?.id}
              options={categories?.map((category) => ({
                label: category.name,
                value: category.id,
              }))}
            />
            <EditProductTagForm
              product_tag={response?.product?.tags?.map((tag) => ({
                name: tag.name,
                id: tag.id,
              }))}
              id={response?.product?.id}
            />
            <EditProductBriefDescriptionForm
              product_brief_description={response.product.description}
              id={response?.product?.id}
            />
            <EditProductManufacturerForm
              manufacturer={response.product.manufacturer}
              id={response?.product?.id}
            />
            <EditProductDiscountForm
              initialData={response.product}
              id={response?.product?.id}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default EditProductPage;
