import React from "react";
import DashboardHeader from "../_components/dashboard/header";
import CategoryTable from "@/components/ecommerce/table/category/category-table";

export const metadata = {
  title: "Admin Dashboard | Categories",
  description: "Generated by create next app",
};

const CategoryPage = ({ searchParams }) => {
  let params = "";
  let label = "";

  if (searchParams.tab === "store") {
    params = "/dashboard/ecommerce";
    label = "Store";
  } else if (searchParams.tab === "training") {
    params = "/dashboard/ecommerce";
    label = "Training";
  }

  const breadcrumbs = [
    { name: "Dashboard", href: "/dashboard" },
    ...(params ? [{ name: label, href: params }] : []),
    { name: "Category" },
  ];

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] min-h-screen space-y-4">
        <div className="w-full">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-2xl font-bold">{label} Categories</h1>
            </div>
          </div>
          <CategoryTable />
        </div>
      </div>
    </>
  );
};

export default CategoryPage;
