import React from "react";
import DashboardHeader from "../../_components/dashboard/header";
import BlogTitleForm from "../_components/form/blog-title-form";
import BlogDescriptionForm from "../_components/form/blog-description-form";
import BlogCategoryForm from "../_components/form/blog-category-form";
import BlogImageUploadForm from "../_components/form/blog-image-upload-form";
import BlogSubmitButton from "../_components/form/blog-submit-button";
export const metadata = {
  title: "Admin Dashboard | New Blog",
  keywords: "admin, dashboard, blog, create, new blog",
  description: "Generated by create next app",
};

const NewBlog = () => {
  const breadcrumbs = [
    { name: "Dashboard", href: "/dashboard" },
    { name: "Blogs and Articles", href: "/dashboard/blog" },
    { name: "New Blog" },
  ];

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] space-y-4">
        <h1 className="font-bold text-[20px]">Publish an article</h1>
        <div className="w-full flex md:flex-row flex-col gap-5 justify-between">
          <div className="w-full space-y-5  h-fit ">
            <BlogTitleForm />
            <BlogCategoryForm />
            <BlogDescriptionForm />
            <BlogImageUploadForm />
            <BlogSubmitButton />
          </div>
        </div>
      </div>
    </>
  );
};

export default NewBlog;
