import React from "react";

import DashboardHeader from "../_components/dashboard/header";
import Table from "./_component/table";

export const metadata = {
  title: "Admin Dashboard | Competition",
  description: "Generated by create next app",
};

const ProjectPage = () => {
  const breadcrumbs = [
    { name: "Dashboard", href: "/dashboard" },
    { name: "Competitions" },
  ];

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] min-h-screen space-y-4">
        <div className="w-full">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-2xl font-bold">Competition Management</h1>
            </div>
          </div>
          <Table />
        </div>
      </div>
    </>
  );
};

export default ProjectPage;
