import {
  getAllCategories,
  getSingleProject,
} from "@/service/project/projectService";
import DashboardHeader from "../../../_components/dashboard/header";
import EditProjectTitleForm from "../../_component/form/edit-project-title-form";
import EditProjectCategoryForm from "../../_component/form/edit-project-category-form";
import ProjectMediaTypeForm from "../../_component/form/project-media-type-form";
import EditBlogImageUploadForm from "../../../blog/_components/form/edit-blog-image-upload-form";
import EditProjectFileUploadForm from "../../_component/form/edit-project-file-upload-form";
import EditProjectDescriptionForm from "../../_component/form/edit-contest-description-form";

export const metadata = {
  title: "Admin Dashboard | Edit Project",
  description: "Generated by create next app",
};

const breadcrumbs = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Project Management", href: "/dashboard/project" },
  { name: "Edit project" },
];

const EditProjectPage = async ({ params }) => {
  const response = await getSingleProject(params.projectId);
  const { allCategories } = await getAllCategories();

  return (
    <>
      <DashboardHeader breadcrumbs={breadcrumbs} />
      <div className="p-6 bg-[whitesmoke] space-y-4">
        <h1 className="font-bold text-[20px]">Edit Project</h1>
        <div className="w-full flex md:flex-row flex-col gap-5 justify-between">
          <div className="w-full space-y-5  h-fit ">
            <EditProjectTitleForm
              name={response?.project?.title}
              id={response?.project?.id}
            />
            <EditProjectCategoryForm
              id={response?.project?.id}
              options={allCategories?.map((category) => ({
                label: category.title,
                value: category.id,
              }))}
            />
            <ProjectMediaTypeForm />
            <EditProjectFileUploadForm
              mediaDoc={response?.project?.mediaDoc}
              id={response?.project?.id}
            />
            <EditProjectDescriptionForm
              description={response?.project?.description}
              id={response?.project?.id}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default EditProjectPage;
